### ISSUE TITLE
Improve pip package

### ISSUE THREAD

**Issue by jancura** [pmeletis/panoptic_parts#2]

**Comment by pmeletis** [comment]
pip package is created.

**Comment by pmeletis** [comment]
Find a way to automatically install pycocotools module from https://github.com/cocodataset/cocoapi, so running `pp_merge_to_panoptic` goes smoothly.

**Comment by pmeletis** [comment]
When installing on Windows `pip install pycocotools` requires MSCV compiler, which makes installation cumbersome as build tools are not by default installed in Windows.
Does it require extra dependencies in a "fresh" linux?
Maybe consider moving it to optional.txt again? (as it is used only on specific scripts) @vincentwen1995 @DdeGeus

**Comment by vincentwen1995** [comment]
Hi Panos, I think it's because pycocotools has some C/C++ dependency that needs to be built.

I only tested it out with gcc on my wsl environment.

Indeed if it is not a pure python package and either gcc/msvc compiler is needed, we should make it optional or note it down in Readme.
________________________________

**Comment by pmeletis** [comment]
ok, it's included now.
