### ISSUE TITLE
some pids and sids are not aligned in Pascal?

### ISSUE THREAD

**Issue by xushilin1** [pmeletis/panoptic_parts#21]
For the Pascal dataset, the evalspec.eval_sid_pid_total has 57 parts, including  401, 901, 1101,  1801, 1901...; But the sids (4, 9, 11, 18 19) corresponding to these pids not included in evalspec.eval_sid_parts and dataspec.l_parts; 
So, how many parts and things I should use when training?

**Comment by DdeGeus** [comment]
Hi @xushilin1, thanks for your interest in our work!

You are correct that in the [eval_spec]( https://github.com/pmeletis/panoptic_parts/blob/master/panoptic_parts/specs/eval_specs/ppq_ppp_59_57_cvpr21_default_evalspec.yaml), we define pids for 20 sids (i.e., 1…20). We do this to be fully consistent with the 58 classes (57 parts + background) that are used in existing part segmentation works (e.g., [BSANet](https://openaccess.thecvf.com/content_ICCV_2019/html/Zhao_Multi-Class_Part_Parsing_With_Joint_Boundary-Semantic_Awareness_ICCV_2019_paper.html)), so that we could directly use existing models to create our state-of-the-art baselines, and be as comparable as possible with earlier work. 

However, for 5 of these scene-level classes (sids 4, 9, 11, 18, 19), only one part class is defined. This means that the part segmentation mask is equal to the instance mask for those particular classes; there is no further hierarchy. For this reason, we decided that for PartPQ evaluation, we do not evaluate those 5 classes on part-level as this does not make sense.

So to conclude, if you want to use exactly the same training setting as the baselines in our paper, or directly compare the part-level mean IOU, you should train on all 57 part-level classes. However, for the Part-aware Panoptic Segmentation task as a whole, and to directly compare the PartPQ, it is sufficient to train on 52 part-level classes (excluding 401, 901, 1101, 1801, 1901). Note: training on all 57 part classes does not lead to problems, as in that case the aforementioned 5 part classes will simply be ignored during merging and evaluation.
